databases:
  - name: stock-prediction-db
    plan: free

services:
  - type: web
    name: stock-prediction-backend
    runtime: python
    rootDir: backend-drf
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn stock_prediction.wsgi:application --workers 1 --threads 2 --timeout 120"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: PYTHON_VERSION
        value: "3.12.3"
      - key: DATABASE_URL
        fromDatabase:
          name: stock-prediction-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: CORS_ALLOWED_ORIGINS
        value: "https://stock-prediction-frontend.onrender.com"
      - key: CSRF_TRUSTED_ORIGINS
        value: "https://stock-prediction-backend.onrender.com"
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "3"
      - key: TF_NUM_INTRAOP_THREADS
        value: "1"
      - key: TF_NUM_INTEROP_THREADS
        value: "1"
      - key: OMP_NUM_THREADS
        value: "1"

  - type: web
    name: stock-prediction-frontend
    runtime: static
    rootDir: frontend-react/stock-prediction-portal
    buildCommand: "npm install && npm run build"
    staticPublishPath: dist
    envVars:
      - key: VITE_API_BASE_URL
        value: "https://stock-prediction-backend.onrender.com/"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
